CREATE DATABASE events

USE events

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE event (
  id INT AUTO_INCREMENT PRIMARY KEY,
  eventTitle VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  time TIME NOT NULL,
  location VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  hostName VARCHAR(255) NOT NULL,
  attendees JSON  NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);